// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtp8vzm2m_yyvbrMiD8WhOFXwERr-EH78',
    appId: '1:881075334135:web:a63076bb9abdb00b819cf2',
    messagingSenderId: '881075334135',
    projectId: 'doctor-hunt-3a15d',
    authDomain: 'doctor-hunt-3a15d.firebaseapp.com',
    storageBucket: 'doctor-hunt-3a15d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1jDi4lvC_Rtqk8G0Mnnw_nlO0k8LmurE',
    appId: '1:881075334135:android:822b7e73a82dc4c7819cf2',
    messagingSenderId: '881075334135',
    projectId: 'doctor-hunt-3a15d',
    storageBucket: 'doctor-hunt-3a15d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd2Gn_h2MxU3Xsyiq6cYuw_Gw4ehPVIWg',
    appId: '1:881075334135:ios:fa5f87185a4dec39819cf2',
    messagingSenderId: '881075334135',
    projectId: 'doctor-hunt-3a15d',
    storageBucket: 'doctor-hunt-3a15d.firebasestorage.app',
    iosBundleId: 'com.abdallahelnshar.doctorHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd2Gn_h2MxU3Xsyiq6cYuw_Gw4ehPVIWg',
    appId: '1:881075334135:ios:fa5f87185a4dec39819cf2',
    messagingSenderId: '881075334135',
    projectId: 'doctor-hunt-3a15d',
    storageBucket: 'doctor-hunt-3a15d.firebasestorage.app',
    iosBundleId: 'com.abdallahelnshar.doctorHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtp8vzm2m_yyvbrMiD8WhOFXwERr-EH78',
    appId: '1:881075334135:web:f59000abf312ce03819cf2',
    messagingSenderId: '881075334135',
    projectId: 'doctor-hunt-3a15d',
    authDomain: 'doctor-hunt-3a15d.firebaseapp.com',
    storageBucket: 'doctor-hunt-3a15d.firebasestorage.app',
  );
}
